export type BusinessType = "hotel" | "restaurant" | "saas" | "retail" | "clinic" | "fitness" | "other";

export interface BusinessPreset {
  label: string;
  categories: Record<string, number>;
  templates: Record<string, string[]>;
  placeholders: {
    actionVerb: string;
    bookVerb: string;
    unitNoun: string;
  };
}

export const BUSINESS_PRESETS: Record<BusinessType, BusinessPreset> = {
  hotel: {
    label: "Hotel / Hospitality",
    categories: {
      Discovery: 20,
      Comparison: 15,
      Brand: 15,
      Location: 10,
      Experience: 15,
      Amenity: 10,
      Practical: 10,
      Dining: 5,
    },
    placeholders: {
      actionVerb: "stay at",
      bookVerb: "book",
      unitNoun: "room",
    },
    templates: {
      Discovery: [
        "What are the best {type} hotels in {location}?",
        "Can you recommend a good hotel in {location} for {useCase}?",
        "Where should I stay in {location}?",
        "What hotels in {location} have the best reviews?",
        "I'm looking for a hotel in {location} with {feature}. Any suggestions?",
        "Top rated hotels in {location} under {price} per night",
        "Best places to stay in {location} for first-time visitors",
        "What's the best value hotel in {location}?",
        "Recommend a hotel near the city center in {location}",
        "Which {type} hotel in {location} should I book for a weekend trip?",
      ],
      Comparison: [
        "How does {brand} compare to {competitor} in {location}?",
        "{brand} vs {competitor} — which is better for {useCase}?",
        "Is {brand} better than {competitor}?",
        "What are the pros and cons of {brand} vs {competitor}?",
        "Should I stay at {brand} or {competitor} in {location}?",
        "Compare the top boutique hotels in {location}",
        "Which hotel in {location} has better service, {brand} or {competitor}?",
        "Best alternative to {competitor} in {location}",
      ],
      Brand: [
        "Tell me about {brand} in {location}",
        "What is {brand} known for?",
        "Is {brand} a good hotel? What do people say about it?",
        "What are the reviews like for {brand}?",
        "Is {brand} worth the price?",
        "What makes {brand} special compared to other hotels in {location}?",
        "Has {brand} won any awards?",
        "Describe the experience of staying at {brand}",
      ],
      Location: [
        "Best hotels near downtown {location}",
        "Where to stay near the airport in {location}?",
        "Hotels in {location} with easy access to public transport",
        "What's the best neighborhood to stay in {location}?",
        "Hotels in {location} close to tourist attractions",
        "Is {brand} well located in {location}?",
      ],
      Experience: [
        "Best {location} hotels for {useCase}",
        "Romantic hotels in {location} for couples",
        "Hotels in {location} with the best rooftop bars",
        "Where to stay in {location} for nightlife?",
        "Best hotels in {location} for a luxury weekend",
        "Unique hotel experiences in {location}",
        "Instagram-worthy hotels in {location}",
        "Best hotels in {location} with a pool",
      ],
      Amenity: [
        "Hotels in {location} with {feature}",
        "Best hotel spa in {location}",
        "{location} hotels with free breakfast",
        "Which hotels in {location} have the best gym?",
        "Hotels in {location} with in-room hot tub",
        "Does {brand} in {location} have a pool?",
      ],
      Practical: [
        "How much does it cost to stay at {brand} in {location}?",
        "Best time to visit {location} and where to stay",
        "How do I book a room at {brand}?",
        "Is {location} expensive for hotels?",
        "Tips for booking hotels in {location}",
        "What's the cancellation policy like at {brand}?",
      ],
      Dining: [
        "Hotels in {location} with great restaurants",
        "Best hotel breakfast in {location}",
        "Hotels in {location} known for their food",
        "Where to stay in {location} for food lovers?",
        "Does {brand} have good on-site dining?",
        "Hotels in {location} near the best street food",
      ],
    },
  },

  restaurant: {
    label: "Restaurant / Dining",
    categories: {
      Discovery: 20,
      Comparison: 15,
      Brand: 15,
      Location: 10,
      Menu: 15,
      Ambiance: 10,
      Practical: 10,
      Cuisine: 5,
    },
    placeholders: {
      actionVerb: "eat at",
      bookVerb: "reserve",
      unitNoun: "table",
    },
    templates: {
      Discovery: [
        "What are the best {type} restaurants in {location}?",
        "Can you recommend a great place to eat in {location}?",
        "Where should I have dinner in {location} tonight?",
        "What restaurants in {location} have the best reviews?",
        "I'm looking for a {type} restaurant in {location} with {feature}. Any ideas?",
        "Top rated restaurants in {location} under {price} per person",
        "Best restaurants in {location} for first-time visitors",
        "What's a must-try restaurant in {location}?",
        "Recommend a {type} restaurant near downtown {location}",
        "Which restaurant in {location} should I try for {useCase}?",
      ],
      Comparison: [
        "How does {brand} compare to {competitor} in {location}?",
        "{brand} vs {competitor} — which has better food?",
        "Is {brand} better than {competitor} for {useCase}?",
        "What are the pros and cons of eating at {brand} vs {competitor}?",
        "Should I go to {brand} or {competitor} for dinner in {location}?",
        "Best alternative to {competitor} in {location}",
        "Which has better service, {brand} or {competitor}?",
        "Compare the best {type} restaurants in {location}",
      ],
      Brand: [
        "Tell me about {brand} in {location}",
        "What is {brand} known for?",
        "Is {brand} worth eating at? What do people say?",
        "What are the reviews like for {brand} restaurant?",
        "Is {brand} overpriced for what you get?",
        "What makes {brand} stand out from other restaurants in {location}?",
        "Has {brand} been reviewed by any food critics?",
        "What's the story behind {brand} restaurant?",
      ],
      Location: [
        "Best restaurants near downtown {location}",
        "Where to eat near the waterfront in {location}?",
        "Restaurants in {location} within walking distance of major attractions",
        "What's the best food neighborhood in {location}?",
        "Is {brand} easy to get to in {location}?",
        "Restaurants in {location} with outdoor seating and a view",
      ],
      Menu: [
        "What should I order at {brand}?",
        "What's on the menu at {brand} in {location}?",
        "Does {brand} have good vegetarian options?",
        "Best dishes to try at {brand}",
        "Does {brand} have a tasting menu?",
        "What's the signature dish at {brand}?",
        "Does {brand} accommodate food allergies?",
        "How's the wine list at {brand}?",
      ],
      Ambiance: [
        "Best restaurants in {location} for {useCase}",
        "Romantic restaurants in {location} for a date night",
        "Restaurants in {location} with the best atmosphere",
        "Where's a good quiet restaurant in {location} for a business dinner?",
        "Best restaurants in {location} with live music",
        "Instagram-worthy restaurants in {location}",
      ],
      Practical: [
        "How much does dinner cost at {brand}?",
        "Do I need a reservation at {brand} in {location}?",
        "What are the opening hours for {brand}?",
        "Does {brand} take walk-ins?",
        "Is there parking near {brand} in {location}?",
        "Tips for getting a table at popular restaurants in {location}",
      ],
      Cuisine: [
        "Best {type} food in {location}",
        "Where to find authentic {type} cuisine in {location}?",
        "What {type} restaurants are popular in {location}?",
        "Underrated {type} spots in {location}",
        "Who makes the best {type} dishes in {location}?",
        "Is {brand} considered authentic {type} cuisine?",
      ],
    },
  },

  saas: {
    label: "SaaS / Software",
    categories: {
      Discovery: 20,
      Comparison: 20,
      Brand: 15,
      Features: 15,
      Pricing: 10,
      Integration: 10,
      Support: 5,
      Security: 5,
    },
    placeholders: {
      actionVerb: "use",
      bookVerb: "subscribe to",
      unitNoun: "plan",
    },
    templates: {
      Discovery: [
        "What are the best {type} tools available right now?",
        "Can you recommend a good {type} platform for {useCase}?",
        "What {type} software do most companies use?",
        "What are the top-rated {type} tools in 2025?",
        "I need a {type} solution with {feature}. What are my options?",
        "Best {type} tools for small businesses under {price} per month",
        "What {type} software would you recommend for a startup?",
        "Which {type} tool has the best user experience?",
        "What's the best free {type} tool available?",
        "Recommend a {type} platform that's easy to set up",
      ],
      Comparison: [
        "How does {brand} compare to {competitor}?",
        "{brand} vs {competitor} — which is better for {useCase}?",
        "Is {brand} better than {competitor} for small teams?",
        "What are the pros and cons of {brand} vs {competitor}?",
        "Should I switch from {competitor} to {brand}?",
        "Best alternative to {competitor} in the {type} space",
        "Which has better features, {brand} or {competitor}?",
        "Compare the top {type} platforms side by side",
        "{brand} vs {competitor} pricing and features breakdown",
        "Which is easier to use, {brand} or {competitor}?",
      ],
      Brand: [
        "Tell me about {brand}",
        "What is {brand} used for?",
        "Is {brand} any good? What do users say?",
        "What are the reviews like for {brand}?",
        "Is {brand} worth the price?",
        "What makes {brand} different from other {type} tools?",
        "Who uses {brand}? What kind of companies?",
        "What's the reputation of {brand} in the industry?",
      ],
      Features: [
        "What features does {brand} offer?",
        "Does {brand} have {feature}?",
        "What's the best {type} tool for {feature}?",
        "Can {brand} handle {useCase}?",
        "What are the key features to look for in a {type} tool?",
        "Does {brand} offer {feature} out of the box?",
        "What's {brand}'s best feature compared to competitors?",
        "Is {brand} good for {useCase}?",
      ],
      Pricing: [
        "How much does {brand} cost?",
        "Is {brand} expensive compared to {competitor}?",
        "Does {brand} have a free tier?",
        "What's the pricing for {brand}'s enterprise plan?",
        "Best {type} tools under {price} per month",
        "Is {brand} worth the price for a small team?",
      ],
      Integration: [
        "Does {brand} integrate with Slack?",
        "What integrations does {brand} support?",
        "Can I connect {brand} with {competitor}?",
        "Does {brand} have an API?",
        "Best {type} tools that integrate with popular CRMs",
        "How easy is it to set up integrations with {brand}?",
      ],
      Support: [
        "Is {brand}'s customer support any good?",
        "Does {brand} offer 24/7 support?",
        "What's the onboarding experience like with {brand}?",
        "How responsive is {brand}'s support team?",
        "Does {brand} have good documentation and tutorials?",
        "What kind of support does {brand} provide?",
      ],
      Security: [
        "Is {brand} secure? What certifications do they have?",
        "Does {brand} comply with GDPR?",
        "What security features does {brand} offer?",
        "Is my data safe with {brand}?",
        "Does {brand} support SSO and two-factor authentication?",
        "How does {brand} handle data privacy?",
      ],
    },
  },

  retail: {
    label: "Retail / E-commerce",
    categories: {
      Discovery: 20,
      Comparison: 15,
      Brand: 15,
      Products: 15,
      Location: 10,
      Experience: 10,
      Practical: 10,
      Value: 5,
    },
    placeholders: {
      actionVerb: "visit",
      bookVerb: "buy from",
      unitNoun: "product",
    },
    templates: {
      Discovery: [
        "What are the best {type} stores in {location}?",
        "Where can I buy good {type} products in {location}?",
        "Can you recommend a {type} shop in {location}?",
        "What {type} brands have the best reviews?",
        "I'm looking for a store in {location} that sells {feature}. Any ideas?",
        "Top rated {type} stores in {location}",
        "Best {type} retailers for first-time buyers",
        "What's the best place to shop for {type} products online?",
        "Recommend a {type} store with great customer service",
        "Which {type} store in {location} has the widest selection?",
      ],
      Comparison: [
        "How does {brand} compare to {competitor}?",
        "{brand} vs {competitor} — which has better products?",
        "Is {brand} better than {competitor} for {useCase}?",
        "What are the pros and cons of shopping at {brand} vs {competitor}?",
        "Should I buy from {brand} or {competitor}?",
        "Best alternative to {competitor} for {type} products",
        "Which store has better quality, {brand} or {competitor}?",
        "Compare {brand} and {competitor} for value and selection",
      ],
      Brand: [
        "Tell me about {brand}",
        "What is {brand} known for?",
        "Is {brand} a good store? What do customers say?",
        "What are the reviews like for {brand}?",
        "Is {brand} worth shopping at?",
        "What makes {brand} stand out from other {type} retailers?",
        "Does {brand} have a good reputation?",
        "What's the return policy at {brand}?",
      ],
      Products: [
        "What products does {brand} sell?",
        "What's the best-selling item at {brand}?",
        "Does {brand} carry {feature}?",
        "What brands does {brand} stock?",
        "Best {type} products available at {brand}",
        "What new products has {brand} released recently?",
        "Is {brand}'s product quality good for the price?",
        "What should I buy at {brand}?",
      ],
      Location: [
        "Where is the nearest {brand} store in {location}?",
        "Best {type} shops near downtown {location}",
        "Does {brand} have a store in {location}?",
        "What are the best shopping areas in {location}?",
        "Is there a {brand} outlet near {location}?",
        "Which {type} stores in {location} are worth visiting?",
      ],
      Experience: [
        "What's the shopping experience like at {brand}?",
        "Does {brand} have good customer service?",
        "Is {brand} crowded on weekends?",
        "What's {brand}'s store layout like?",
        "Does {brand} offer personal shopping or styling?",
        "Best {type} shopping experiences in {location}",
      ],
      Practical: [
        "What are the hours for {brand} in {location}?",
        "Does {brand} offer online ordering with in-store pickup?",
        "What's {brand}'s return policy?",
        "Does {brand} ship internationally?",
        "How long does delivery take from {brand}?",
        "Does {brand} have a loyalty program?",
      ],
      Value: [
        "Is {brand} expensive?",
        "When does {brand} have sales?",
        "Best deals at {brand} right now",
        "Does {brand} offer price matching?",
        "Is {brand} good value for money compared to {competitor}?",
        "Best affordable {type} stores in {location}",
      ],
    },
  },

  clinic: {
    label: "Medical Clinic / Healthcare",
    categories: {
      Discovery: 20,
      Comparison: 15,
      Brand: 15,
      Services: 15,
      Location: 10,
      Experience: 10,
      Practical: 10,
      Specialization: 5,
    },
    placeholders: {
      actionVerb: "visit",
      bookVerb: "book",
      unitNoun: "appointment",
    },
    templates: {
      Discovery: [
        "What are the best {type} clinics in {location}?",
        "Can you recommend a good {type} doctor in {location}?",
        "Where should I go for {useCase} treatment in {location}?",
        "What clinics in {location} have the best patient reviews?",
        "I need a {type} clinic in {location} with {feature}. Any suggestions?",
        "Top rated {type} clinics in {location}",
        "Best {type} providers for new patients in {location}",
        "Who's the best {type} specialist in {location}?",
        "Recommend a {type} clinic near downtown {location}",
        "Which {type} clinic in {location} accepts walk-ins?",
      ],
      Comparison: [
        "How does {brand} compare to {competitor} in {location}?",
        "{brand} vs {competitor} — which clinic is better for {useCase}?",
        "Is {brand} better than {competitor} for {type} care?",
        "What are the differences between {brand} and {competitor}?",
        "Should I go to {brand} or {competitor} in {location}?",
        "Best alternative to {competitor} for {type} services in {location}",
        "Which clinic has shorter wait times, {brand} or {competitor}?",
        "Compare patient satisfaction at {brand} vs {competitor}",
      ],
      Brand: [
        "Tell me about {brand} clinic in {location}",
        "What is {brand} known for?",
        "Is {brand} a good clinic? What do patients say?",
        "What are the reviews like for {brand}?",
        "Is {brand} worth the cost?",
        "What makes {brand} different from other {type} clinics in {location}?",
        "Does {brand} have board-certified doctors?",
        "What's the reputation of {brand} in {location}?",
      ],
      Services: [
        "What services does {brand} offer?",
        "Does {brand} provide {feature}?",
        "What {type} treatments are available at {brand}?",
        "Can {brand} help with {useCase}?",
        "What procedures does {brand} specialize in?",
        "Does {brand} offer telehealth appointments?",
        "What diagnostic services does {brand} have?",
        "Does {brand} offer preventive care programs?",
      ],
      Location: [
        "Where is {brand} located in {location}?",
        "Best {type} clinics near downtown {location}",
        "Is there a {brand} clinic near me in {location}?",
        "Which {type} clinics in {location} have easy parking?",
        "Clinics in {location} accessible by public transport",
        "{type} clinics with multiple locations in {location}",
      ],
      Experience: [
        "What's the patient experience like at {brand}?",
        "How are the doctors at {brand}?",
        "Is the staff at {brand} friendly and professional?",
        "How long are the typical wait times at {brand}?",
        "Does {brand} make you feel comfortable as a patient?",
        "What's the bedside manner like at {brand}?",
      ],
      Practical: [
        "How do I book an appointment at {brand}?",
        "Does {brand} accept my insurance?",
        "What are the hours for {brand} in {location}?",
        "Does {brand} offer weekend appointments?",
        "How much does a consultation cost at {brand}?",
        "What insurance plans does {brand} accept?",
      ],
      Specialization: [
        "What does {brand} specialize in?",
        "Best clinic in {location} for {useCase}",
        "Which {type} clinics in {location} are experts in {feature}?",
        "Does {brand} have specialists for {useCase}?",
        "Where can I get specialized {type} treatment in {location}?",
        "Is {brand} a specialist or general {type} practice?",
      ],
    },
  },

  fitness: {
    label: "Gym / Fitness Center",
    categories: {
      Discovery: 20,
      Comparison: 15,
      Brand: 15,
      Facilities: 15,
      Location: 10,
      Experience: 10,
      Practical: 10,
      Programs: 5,
    },
    placeholders: {
      actionVerb: "visit",
      bookVerb: "join",
      unitNoun: "membership",
    },
    templates: {
      Discovery: [
        "What are the best {type} gyms in {location}?",
        "Can you recommend a good gym in {location} for {useCase}?",
        "Where should I work out in {location}?",
        "What gyms in {location} have the best reviews?",
        "I'm looking for a {type} gym in {location} with {feature}. Any suggestions?",
        "Top rated fitness centers in {location} under {price} per month",
        "Best gyms in {location} for beginners",
        "What's the best value gym in {location}?",
        "Recommend a {type} fitness center near downtown {location}",
        "Which gym in {location} should I join for {useCase}?",
      ],
      Comparison: [
        "How does {brand} compare to {competitor} in {location}?",
        "{brand} vs {competitor} — which gym is better for {useCase}?",
        "Is {brand} better than {competitor}?",
        "What are the pros and cons of {brand} vs {competitor}?",
        "Should I join {brand} or {competitor} in {location}?",
        "Best alternative to {competitor} for {type} fitness in {location}",
        "Which gym has better equipment, {brand} or {competitor}?",
        "Compare memberships at {brand} and {competitor}",
      ],
      Brand: [
        "Tell me about {brand} gym in {location}",
        "What is {brand} known for?",
        "Is {brand} a good gym? What do members say?",
        "What are the reviews like for {brand}?",
        "Is {brand} worth the membership fee?",
        "What makes {brand} different from other gyms in {location}?",
        "Does {brand} have certified personal trainers?",
        "What's the vibe like at {brand}?",
      ],
      Facilities: [
        "What facilities does {brand} have?",
        "Does {brand} have {feature}?",
        "What equipment does {brand} offer?",
        "Does {brand} have a pool or sauna?",
        "Is {brand}'s facility well maintained?",
        "What's the best gym in {location} for {feature}?",
        "Does {brand} have separate areas for cardio and weights?",
        "How big is {brand}'s gym floor?",
      ],
      Location: [
        "Where is {brand} located in {location}?",
        "Best gyms near downtown {location}",
        "Is there a {brand} gym near me in {location}?",
        "Which gyms in {location} have good parking?",
        "Gyms in {location} easy to get to by public transport",
        "Does {brand} have multiple locations in {location}?",
      ],
      Experience: [
        "What's the atmosphere like at {brand}?",
        "Is {brand} crowded during peak hours?",
        "How are the trainers at {brand}?",
        "Is {brand} beginner-friendly?",
        "What's the community like at {brand}?",
        "Does {brand} have a supportive environment for newcomers?",
      ],
      Practical: [
        "How much does a membership at {brand} cost?",
        "Does {brand} offer a free trial?",
        "What are the hours for {brand} in {location}?",
        "Is there a contract or can I cancel anytime at {brand}?",
        "Does {brand} offer family or couple memberships?",
        "What's included in {brand}'s basic membership?",
      ],
      Programs: [
        "What fitness classes does {brand} offer?",
        "Does {brand} have personal training programs?",
        "Best gym in {location} for {useCase}",
        "Does {brand} offer group fitness classes?",
        "What specialty programs does {brand} have?",
        "Does {brand} offer nutrition coaching?",
      ],
    },
  },

  other: {
    label: "Other Business",
    categories: {
      Discovery: 25,
      Comparison: 20,
      Brand: 20,
      Features: 15,
      Practical: 10,
      Value: 10,
    },
    placeholders: {
      actionVerb: "visit",
      bookVerb: "book",
      unitNoun: "service",
    },
    templates: {
      Discovery: [
        "What are the best {type} businesses in {location}?",
        "Can you recommend a good {type} provider in {location}?",
        "Where can I find a reliable {type} service in {location}?",
        "What {type} companies in {location} have the best reviews?",
        "I'm looking for a {type} provider with {feature}. Any suggestions?",
        "Top rated {type} businesses in {location}",
        "Best {type} services for {useCase}",
        "What's the best {type} provider near me in {location}?",
        "Recommend a {type} business that's highly rated",
        "Which {type} service in {location} should I try?",
      ],
      Comparison: [
        "How does {brand} compare to {competitor}?",
        "{brand} vs {competitor} — which is better for {useCase}?",
        "Is {brand} better than {competitor}?",
        "What are the pros and cons of {brand} vs {competitor}?",
        "Should I go with {brand} or {competitor}?",
        "Best alternative to {competitor} for {type} services",
        "Which {type} provider has better quality, {brand} or {competitor}?",
        "Compare {brand} and {competitor} for value and service",
        "Who do people prefer, {brand} or {competitor}?",
        "What's the difference between {brand} and {competitor}?",
      ],
      Brand: [
        "Tell me about {brand}",
        "What is {brand} known for?",
        "Is {brand} any good? What do people say?",
        "What are the reviews like for {brand}?",
        "Is {brand} worth it?",
        "What makes {brand} different from competitors?",
        "Does {brand} have a good reputation?",
        "How long has {brand} been in business?",
        "What do customers like most about {brand}?",
        "Has {brand} received any notable awards or recognition?",
      ],
      Features: [
        "What does {brand} offer?",
        "Does {brand} have {feature}?",
        "What's the best {type} provider for {feature}?",
        "Can {brand} handle {useCase}?",
        "What key features should I look for in a {type} service?",
        "Does {brand} offer anything unique compared to others?",
        "What are {brand}'s main strengths?",
        "Is {brand} good for {useCase}?",
      ],
      Practical: [
        "How do I contact {brand}?",
        "What are {brand}'s hours of operation?",
        "How much does {brand} charge for their services?",
        "Does {brand} serve the {location} area?",
        "What's the process for getting started with {brand}?",
        "Does {brand} offer online booking or services?",
      ],
      Value: [
        "Is {brand} expensive?",
        "What does {brand} cost compared to {competitor}?",
        "Best affordable {type} services in {location}",
        "Is {brand} good value for money?",
        "Does {brand} have any current promotions or discounts?",
        "What's the best budget-friendly {type} option in {location}?",
      ],
    },
  },
};

export function getDefaultCategories(type: BusinessType): Record<string, number> {
  return { ...BUSINESS_PRESETS[type].categories };
}
